# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accaunt_wigit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(938, 600)
        self.accaunt_wigit = QtWidgets.QFrame(form)
        self.accaunt_wigit.setGeometry(QtCore.QRect(-1, 19, 1000, 600))
        self.accaunt_wigit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accaunt_wigit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accaunt_wigit.setObjectName("accaunt_wigit")
        self.ac_accaunt_name = QtWidgets.QLabel(self.accaunt_wigit)
        self.ac_accaunt_name.setGeometry(QtCore.QRect(10, 10, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.ac_accaunt_name.setFont(font)
        self.ac_accaunt_name.setObjectName("ac_accaunt_name")
        self.ac_login = QtWidgets.QPushButton(self.accaunt_wigit)
        self.ac_login.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.ac_login.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.ac_login.setObjectName("ac_login")
        self.ac_sing_out = QtWidgets.QPushButton(self.accaunt_wigit)
        self.ac_sing_out.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.ac_sing_out.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.ac_sing_out.setObjectName("ac_sing_out")
        self.ac_view_balls = QtWidgets.QLabel(self.accaunt_wigit)
        self.ac_view_balls.setGeometry(QtCore.QRect(6, 482, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.ac_view_balls.setFont(font)
        self.ac_view_balls.setObjectName("ac_view_balls")
        self.listView = QtWidgets.QListView(self.accaunt_wigit)
        self.listView.setGeometry(QtCore.QRect(475, 70, 451, 461))
        self.listView.setStyleSheet("\n"
"background-color: rgb(173, 149, 134);")
        self.listView.setObjectName("listView")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.ac_accaunt_name.setText(_translate("form", "AccauntName"))
        self.ac_login.setText(_translate("form", "Войти"))
        self.ac_sing_out.setText(_translate("form", "Выйти"))
        self.ac_view_balls.setText(_translate("form", "Полученно баллов 10/1000"))
