# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blimb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.blind = QtWidgets.QWidget(Form)
        self.blind.setGeometry(QtCore.QRect(0, 0, 1001, 21))
        self.blind.setStyleSheet("background-color: rgb(86, 51, 26);")
        self.blind.setObjectName("blind")
        self.b_theory_button = QtWidgets.QPushButton(self.blind)
        self.b_theory_button.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.b_theory_button.setStyleSheet("background-color: rgb(194, 159, 133);")
        self.b_theory_button.setObjectName("b_theory_button")
        self.b_accaunt_button = QtWidgets.QPushButton(self.blind)
        self.b_accaunt_button.setGeometry(QtCore.QRect(920, 0, 75, 23))
        self.b_accaunt_button.setStyleSheet("background-color: rgb(194, 159, 133);")
        self.b_accaunt_button.setObjectName("b_accaunt_button")
        self.b_test_button = QtWidgets.QPushButton(self.blind)
        self.b_test_button.setGeometry(QtCore.QRect(80, 0, 75, 23))
        self.b_test_button.setStyleSheet("background-color: rgb(194, 159, 133);")
        self.b_test_button.setObjectName("b_test_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b_theory_button.setText(_translate("Form", "Учить"))
        self.b_accaunt_button.setText(_translate("Form", "Аккаунт"))
        self.b_test_button.setText(_translate("Form", "Тесты"))
