# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setStyleSheet("background-color: rgb(194, 168, 150);\n"
"")
        self.welcomE_wigit = QtWidgets.QWidget(MainWindow)
        self.welcomE_wigit.setObjectName("welcomE_wigit")
        self.w_start = QtWidgets.QPushButton(self.welcomE_wigit)
        self.w_start.setGeometry(QtCore.QRect(400, 200, 251, 181))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.w_start.setFont(font)
        self.w_start.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.w_start.setObjectName("w_start")
        MainWindow.setCentralWidget(self.welcomE_wigit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.w_start.setText(_translate("MainWindow", "Начать обучение"))
