# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_wigit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.test_theme_get = QtWidgets.QFrame(Form)
        self.test_theme_get.setGeometry(QtCore.QRect(0, 20, 1000, 600))
        self.test_theme_get.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_theme_get.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_theme_get.setObjectName("test_theme_get")
        self.te_forth = QtWidgets.QPushButton(self.test_theme_get)
        self.te_forth.setGeometry(QtCore.QRect(640, 240, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.te_forth.setFont(font)
        self.te_forth.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.te_forth.setObjectName("te_forth")
        self.te_second = QtWidgets.QPushButton(self.test_theme_get)
        self.te_second.setGeometry(QtCore.QRect(320, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.te_second.setFont(font)
        self.te_second.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.te_second.setObjectName("te_second")
        self.te_third = QtWidgets.QPushButton(self.test_theme_get)
        self.te_third.setGeometry(QtCore.QRect(480, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.te_third.setFont(font)
        self.te_third.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.te_third.setObjectName("te_third")
        self.te_first = QtWidgets.QPushButton(self.test_theme_get)
        self.te_first.setGeometry(QtCore.QRect(160, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.te_first.setFont(font)
        self.te_first.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(157, 118, 90);")
        self.te_first.setObjectName("te_first")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.te_forth.setText(_translate("Form", "Четвертое поколение"))
        self.te_second.setText(_translate("Form", "Второе поколение"))
        self.te_third.setText(_translate("Form", "Третье поколение"))
        self.te_first.setText(_translate("Form", "Первое поколение"))
