# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_wigit_answers.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.test_wigit_answers = QtWidgets.QFrame(Form)
        self.test_wigit_answers.setGeometry(QtCore.QRect(0, 20, 1000, 600))
        self.test_wigit_answers.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_wigit_answers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_wigit_answers.setObjectName("test_wigit_answers")
        self.ta_answer = QtWidgets.QLabel(self.test_wigit_answers)
        self.ta_answer.setGeometry(QtCore.QRect(150, 30, 731, 221))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.ta_answer.setFont(font)
        self.ta_answer.setObjectName("ta_answer")
        self.ta_progress = QtWidgets.QProgressBar(self.test_wigit_answers)
        self.ta_progress.setGeometry(QtCore.QRect(50, 530, 921, 23))
        self.ta_progress.setProperty("value", 24)
        self.ta_progress.setObjectName("ta_progress")
        self.ta_fst_answ = QtWidgets.QCheckBox(self.test_wigit_answers)
        self.ta_fst_answ.setGeometry(QtCore.QRect(140, 320, 171, 17))
        self.ta_fst_answ.setObjectName("ta_fst_answ")
        self.ta_sec_answer = QtWidgets.QCheckBox(self.test_wigit_answers)
        self.ta_sec_answer.setGeometry(QtCore.QRect(140, 380, 171, 17))
        self.ta_sec_answer.setObjectName("ta_sec_answer")
        self.ta_therd_answ = QtWidgets.QCheckBox(self.test_wigit_answers)
        self.ta_therd_answ.setGeometry(QtCore.QRect(370, 320, 171, 17))
        self.ta_therd_answ.setObjectName("ta_therd_answ")
        self.ta_fourth_answ = QtWidgets.QCheckBox(self.test_wigit_answers)
        self.ta_fourth_answ.setGeometry(QtCore.QRect(370, 380, 171, 17))
        self.ta_fourth_answ.setObjectName("ta_fourth_answ")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ta_answer.setText(_translate("Form", "TextLabel"))
        self.ta_fst_answ.setText(_translate("Form", "CheckBox"))
        self.ta_sec_answer.setText(_translate("Form", "CheckBox"))
        self.ta_therd_answ.setText(_translate("Form", "CheckBox"))
        self.ta_fourth_answ.setText(_translate("Form", "CheckBox"))
